export const SET_CURRENT_CITY_WEATHER = 'SET_CURRENT_CITY_WEATHER';
export const UPDATE_FAV_CITY_WEATHER = 'UPDATE_FAV_CITY_WEATHER';
export const ADD_TO_FAVS = 'ADD_TO_FAVS';
export const REMOVE_FROM_FAVS = 'REMOVE_FROM_FAVS';
